services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file :
      - .env
    networks:
      - inception
    restart: always
    ports:
      - "3306:3306"

  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always

  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file :
      - .env
    networks:
      - inception
    restart: always
    ports:
      - "9000:9000"

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/yumatsui/mariadb
      o : bind
      type : none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/yumatsui/html
      o : bind
      type : none

networks:
  inception:
    name: inception
    driver: bridge