#version: '3' #dockercomposeのバージョン
#services: #コンテナ定義セクション
#  incep: #名前
#    build: ./requirements/nginx #Dockerfileの場所
#    container_name: nginx
#    ports: #繋げたいポートの指定。左がホスト、右がコンテナのポート番号
#      - "443:443"

services:
  mariadb:
    image: mariadb:user
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file :
      - .env
    networks:
      - inception
    restart: always
    expose:
      - "3306"

  nginx:
    image: nginx:user
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always

  wordpress:
    image: wordpress:user
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file :
      - .env
    networks:
      - inception
    restart: always
    expose:
      - "9000"

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/data/mariadb
      o : bind
      type : none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/data/wordpress
      o : bind
      type : none

networks:
  inception:
    name: inception
    driver: bridge